version: '3.7'

networks:
  app-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
    name: app-net

services:
  ####################
  ## Frontend
  ####################
  frontend:
    build:
      context: ./services/Frontend
      dockerfile: Dockerfile
    ports:
      - '80:8080'
    links:
      - mockapi
    depends_on:
      - mockapi
    networks:
      - app-net
  ####################
  ## Mock API
  ####################
  mockapi:
    build:
      context: ./services/Mockapi
      dockerfile: Dockerfile
    expose:
      - '3001'
    ports:
      - '3001:3001'
    networks:
      - app-net
    command: npm run start
