version: '3.7'

networks:
  app-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
    name: app-net

services:
  ####################
  ## Frontend
  ####################
  frontend:
    build:
      context: ./services/Frontend
      dockerfile: Dockerfile
    ports:
      - '80:${REACT_APP_PORT}'
    links:
      - mockapi
    depends_on:
      - mockapi
    networks:
      - app-net
  ####################
  ## Mock API
  ####################
  mockapi:
    build:
      context: ./services/Mockapi
      dockerfile: Dockerfile
    expose:
      - ${API_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${API_SERVER_PORT}
    ports:
      - '${API_SERVER_PORT}:${API_SERVER_PORT}'
    networks:
      - app-net
    command: npm run start
