version: '3'
services:
  ####################
  ## Frontend
  ####################
  frontend:
    build:
      context: ./services/Frontend
      dockerfile: Dockerfile
    ports:
      - '80:8080'
    depends_on:
      - mockapi
  ####################
  ## Mock API
  ####################
  mockapi:
    build:
      context: ./services/Mockapi
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
