export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR'
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS'
export const SIGNIN_USER_ERROR = 'SIGNIN_USER_ERROR'
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS'
export const SIGNOUT_USER_ERROR = 'SIGNOUT_USER_ERROR'

export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS'
export const FETCH_COURSE_ERROR = 'FETCH_COURSE_ERROR'

export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS'
export const FETCH_STUDENT_ERROR = 'FETCH_STUDENT_ERROR'

export const FETCH_TEACHER_SUCCESS = 'FETCH_TEACHER_SUCCESS'
export const FETCH_TEACHER_ERROR = 'FETCH_TEACHER_ERROR'

export const BEGIN_API_CALL = 'BEGIN_API_CALL'
export const API_CALL_ERROR = 'API_CALL_ERROR'
